const initialState = {
  places: [
    {
      'images': [
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748540975.jpg',
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748540997.png',
      ],
      'available': true,
      'furniture': [
        'sillas',
        'cafe',
        'mueble',
        'sofa',
      ],
      'wifi': false,
      'bath': false,
      'parking': false,
      'tv': false,
      'cleaning': false,
      'closet': false,
      '_id': '5efeac42452502189fa25808',
      'name': 'Increíble departamento a la orilla de  la ciudad',
      'location': 'Suroccidental, El Envigado',
      'price': 30000,
      'size': 100,
      'description': 'Depa en un el mejor lugar de Xalapa en avenida Araucarias, frente a uno de los parques más bonitos de la ciudad, desde el departamento se ven árboles por todos lados y puedes salir a ejercitarte o dar un paseo en cuanto abres la puerta. El depa tiene todo lo necesario para una estancia cómoda;',
      'profileId': '5efd2a8a2ff7b505ae60b416',
      'mainImage': 'https://r-cf.bstatic.com/images/hotel/max1024x768/139/139729897.jpg',
      '__v': 0,
    },
    {
      'images': [
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748609914.jpg',
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748609940.png',
      ],
      'available': true,
      'furniture': [
        'sillas',
        'cafe',
        'mueble',
        'sofa',
      ],
      'wifi': true,
      'bath': false,
      'parking': false,
      'tv': false,
      'cleaning': false,
      'closet': false,
      '_id': '5efeac87da36d118b2d86727',
      'name': 'Increíble departamento a la orilla de  la ciudad',
      'location': 'Suroccidental, El Envigado',
      'price': 30000,
      'size': 100,
      'description': 'Depa en un el mejor lugar de Xalapa en avenida Araucarias, frente a uno de los parques más bonitos de la ciudad, desde el departamento se ven árboles por todos lados y puedes salir a ejercitarte o dar un paseo en cuanto abres la puerta. El depa tiene todo lo necesario para una estancia cómoda;',
      'profileId': '5efd2a8a2ff7b505ae60b416',
      'mainImage': 'https://r-cf.bstatic.com/images/hotel/max1024x768/139/139729897.jpg',
      '__v': 0,
    },
    {
      'images': [
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748709859.jpg',
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748709888.png',
      ],
      'available': true,
      'furniture': [
        'sillas',
        'cafe',
        'mueble',
        'sofa',
      ],
      'wifi': true,
      'bath': false,
      'parking': true,
      'tv': true,
      'cleaning': false,
      'closet': false,
      '_id': '5efeaceb862cf518d479d1b4',
      'name': 'Increíble departamento a la orilla de  la ciudad',
      'location': 'Suroccidental, El Envigado',
      'price': 30000,
      'size': 100,
      'description': 'Depa en un el mejor lugar de Xalapa en avenida Araucarias, frente a uno de los parques más bonitos de la ciudad, desde el departamento se ven árboles por todos lados y puedes salir a ejercitarte o dar un paseo en cuanto abres la puerta. El depa tiene todo lo necesario para una estancia cómoda;',
      'profileId': '5efd2a8a2ff7b505ae60b416',
      'mainImage': 'https://r-cf.bstatic.com/images/hotel/max1024x768/139/139729897.jpg',
      '__v': 0,
    },
    {
      'images': [
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748863704.jpg',
        'https://buscando-roomie.s3.us-east-2.amazonaws.com/1593748863719.png',
      ],
      'available': true,
      'furniture': [
        'sillas',
        'cafe',
        'mueble',
        'sofa',
      ],
      'wifi': true,
      'bath': false,
      'parking': true,
      'tv': true,
      'cleaning': false,
      'closet': false,
      '_id': '5efead84862cf518d479d1b5',
      'name': 'Increíble departamento a la orilla de  la ciudad',
      'location': 'Suroccidental, El Envigado',
      'price': 30000,
      'size': 100,
      'description': 'Depa en un el mejor lugar de Xalapa en avenida Araucarias, frente a uno de los parques más bonitos de la ciudad, desde el departamento se ven árboles por todos lados y puedes salir a ejercitarte o dar un paseo en cuanto abres la puerta. El depa tiene todo lo necesario para una estancia cómoda;',
      'profileId': '5efd2a8a2ff7b505ae60b416',
      'mainImage': 'https://r-cf.bstatic.com/images/hotel/max1024x768/139/139729897.jpg',
      '__v': 0,
    },
  ],
};

export default initialState;
